export const FETCH_TABLE_DATA_REQUEST = 'FETCH_TABLE_DATA_REQUEST';
export const FETCH_TABLE_DATA_SUCCESS = 'FETCH_TABLE_DATA_SUCCESS';
export const FETCH_TABLE_DATA_FAILURE = 'FETCH_TABLE_DATA_FAILURE';

export const FETCH_DISTRIBUTION_TABLE_REQUEST = 'FETCH_DISTRIBUTION_TABLE_REQUEST';
export const FETCH_DISTRIBUTION_TABLE_SUCCESS = 'FETCH_DISTRIBUTION_TABLE_SUCCESS';
export const FETCH_DISTRIBUTION_TABLE_FAILURE = 'FETCH_DISTRIBUTION_TABLE_FAILURE';